name: CI

on:
  - push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install npm
        run: npm install
      - name: Prettier & ESLint
        run: npm run lint
      - name: TypeCheck
        run: npm run typecheck
      - name: Jest
        run: npm run test
